apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: sporteventbook
type: Opaque
stringData:
  APP_KEY: "base64:YourGeneratedAppKey32Characters=="
  DB_PASSWORD: "YourUserPassword123!"
  MIDTRANS_SERVER_KEY: "SB-Mid-server-xxxxx"
  MIDTRANS_CLIENT_KEY: "SB-Mid-client-xxxxx"