apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
  namespace: sporteventbook
  annotations:
    # Nutanix CSI requires StorageType parameter
    # kVolumes = Volume Group, kAppVolumes = App Volume
    csi.nutanix.com/storage-type: kVolumes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nutanix-volume
