apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: sporteventbook
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nutanix-storage
  claimRef:
    namespace: sporteventbook
    name: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sporteventbook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nutanix-storage