apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-scheduler
  namespace: sporteventbook
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: registry.bercalab.my.id/sporteventbook/app:latest
            command:
            - php
            - artisan
            - schedule:run
            envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: harbor-secret
