apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sporteventbook
data:
  # Laravel App
  APP_NAME: "SportEventBook"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://sport.bercalab.my.id"
  
  # Database Connection
  DB_CONNECTION: "mysql"
  
  # Cache & Queue - Redis
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # File Storage - S3/NUS
  FILESYSTEM_DRIVER: "s3"
  
  # Logging
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"